InvalidArchiveError("Error with archive /home/bc3194/.conda/pkgs/python-3.9.7-h12debd9_1v84qlipz/pkg-python-3.9.7-h12debd9_1.tar.zst.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCan't create 'lib/python3.9/__pycache__/sysconfig.cpython-39.pyc'")
InvalidArchiveError("Error with archive /home/bc3194/.conda/pkgs/setuptools-58.0.4-py39h06a4308_0hurcozic/pkg-setuptools-58.0.4-py39h06a4308_0.tar.zst.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCan't create 'lib/python3.9/site-packages/setuptools/_distutils/log.py'")
InvalidArchiveError("Error with archive /home/bc3194/.conda/pkgs/ffmpeg-4.3-hf484d3e_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCan't create 'share/ffmpeg/examples/vaapi_transcode.c'")
InvalidArchiveError("Error with archive /home/bc3194/.conda/pkgs/pip-21.2.4-py39h06a4308_02ajgpbl7/pkg-pip-21.2.4-py39h06a4308_0.tar.zst.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCan't create 'lib/python3.9/site-packages/pip/_vendor/resolvelib/__init__.py'")
InvalidArchiveError("Error with archive /home/bc3194/.conda/pkgs/pytorch-1.10.2-py3.9_cuda11.3_cudnn8.2.0_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCan't create 'lib/python3.9/site-packages/torch/include/ATen/core/Scalar.h'")
InvalidArchiveError("Error with archive /home/bc3194/.conda/pkgs/mkl-service-2.4.0-py39h7f8727e_0p9qgbmif/info-mkl-service-2.4.0-py39h7f8727e_0.tar.zst.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCan't create 'info/test/run_test.py'")
InvalidArchiveError("Error with archive /home/bc3194/.conda/pkgs/freetype-2.11.0-h70c0345_0ir4bldzk/info-freetype-2.11.0-h70c0345_0.tar.zst.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nFailed to create dir 'info/recipe'")
InvalidArchiveError("Error with archive /home/bc3194/.conda/pkgs/gmp-6.2.1-h2531618_2o7f9qw0j/info-gmp-6.2.1-h2531618_2.tar.zst.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCan't create 'info/about.json'")
InvalidArchiveError("Error with archive /home/bc3194/.conda/pkgs/gnutls-3.6.15-he1e5248_0gmm0qu3t/info-gnutls-3.6.15-he1e5248_0.tar.zst.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCan't create 'info/index.json'")
InvalidArchiveError("Error with archive /home/bc3194/.conda/pkgs/nettle-3.7.3-hbbd107a_16z4h_5tr/info-nettle-3.7.3-hbbd107a_1.tar.zst.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nFailed to create dir 'info'")